- pages/search/[lang].js
> Fixed search result title

- components/LeftSidebar.js
- components/Navbar.js
This PR will fixes issue of #31 which is highlighting tags when they are active. 
Fixes #31 
This will fallow code of conduct as of my knowledge.
For further queries feel free to connect.
Hope this will merge as soon as possible.
Happy coding🤝.
> fixex: Highlighting tags when they are active

- README.md
Added a Table of Contents, the license, and  get started section which included a hyper link to the  web application along with instruction on how to begin using the application.
> Update README.md : Added a Table of Contents, License, Get Started section

- pull_request_template.md
Resolve the branch conflicting
> Created pull request for pr template

- components/LeftSidebar.js
- components/Navbar.js
Hi @anand346 ,
I had resolved the issue #29 .
[FEATURE] Make the background blurry when opening sidebar (mobile view) Please merge my PR, If its looks good.
Note: Merge using "Hacktoberfest-accepted" tag.
> #29  Make the background blurry when opening sidebar (mobile view)

- components/IssuesCard.js
- hooks/useHydration.ts
- pages/search/[lang].js
- utils/getTimeFromNow.js
[Issue Link](https://github.com/anand346/findissues/issues/49)
In the issues card component we are introducing regular updating of time elapsed since issue creation. It's updated at an interval of 30 seconds.
The interval of 30 seconds should be good enough for this use case. We can increase it to 60 seconds if we notice a hit on performance and need to reduce the amount of re-renders by half. But on local testing there was hardly any change in rendering performance.
> feat: issuesCard - update time elapsed since issue creation regularly

- README.md
Added list of contributors in the README.md file and also added a 'back to top' button in the same.
- [.] Documentation is updated to reflect the changes.
> added contributors section in README.md file

- components/IssuesCard.js
- pages/search/[lang].js
This is a soulution for issue #52
I made the entire issue card clickable and redirect to the issue page. And now when you hover over a card the time the issue was created shows up.
> Made entire issue card clickable and added hover efect to the time

- _data/repos.js
Added 'Chimoney' to the list of active repos
> chore: Added Chimoney

- _data/repos.js
added 'freecodecamp' in active repos
> chore: added freecodecamp

- helper/Languages.js
Adde 3 new languages shell, matlab and perl.
- [ x] All tests pass successfully.
- [ x] Code adheres to the project's coding standards.
- [ x] Documentation is updated to reflect the changes.
- [ x] No sensitive information is inadvertently exposed.
- [ x] Commit history is clear and concise.
> Added 3 Languages Shell,Matlab and Perl

- _data/repos.js
Added these following active repos:
- `Devlabs`
- `Favirecon`
- `Github Readme Stats`
- `Million.js`
Not required.
Not required.
Not required.
Not required.
> Added more active repos

- _data/repos.js
Reverts anand346/findissues#73
> Revert "Updated repos.js"

- components/LeftSidebar.js
Made 'Active repos' button highlight on visiting `/active-repos`
Made changes in the `LeftSidebar.js` file and added a ternary operator.
> active-repos button highlight

- _data/repos.js
> chore: added 4c-site

- _data/repos.js
added frombricks in active repos
> chore: added frombricks

- _data/repos.js
> added a repo link

- _data/repos.js
Added the [Camunda](https://github.com/camunda/camunda-modeler) repo link for #81 
**Camunda**
1.3k 🌟
<24 hours activity 
Hacktoberfest
Thank you for helpful instructions! Let me know if there are any issues.
> Added one repo link

- _data/repos.js
This repository is active and it's easy. And it's beginner friendly to contribute to.
This PR works on issue #81 .
In this PR, the link to an active repository has been added.
This repository is active. And it's easy and beginner friendly to contribute to this project.
> feat: added repo link

- _data/repos.js
solves #81 
**Summary:**
This pull request addresses the issue #81  : Adding a repository link to the `./_data/repos.js` file.
**Changes Made:**
In this pull request, I have added a repository link to the `./_data/repos.js` file. The added repository meets the following criteria:
- The repository has been updated within the last 3 days.
- The repository has 20 or more stars.
- The repository is currently accepting contributions.
**Repository Link:**
https://github.com/developer-student-clubs/npmBox
**Testing:**
I have tested the changes to ensure that the added repository link correctly fulfills the specified criteria.
Please review this pull request, and if any further modifications or clarifications are needed, I am ready to make them. Thank you for your time and consideration.
> Added a new link in repos.js

- _data/repos.js
Added more active repositories to the file.
> added more repos

- _data/repos.js
[mindsdb
](https://github.com/mindsdb/mindsdb)
- 18.4K stars
- Active
- Accepting new contributors
> added a active repo

- _data/repos.js
> Added facebook/react

- _data/repos.js
First Open Source Contribution🚀
Added the [ortelius](https://github.com/ortelius/ortelius) repo link for #81 
🛠 Proposed Changes
Added Repo :
ortelius
300 🌟
<1 day activity
Hacktoberfest
Additional Context ℹ️
Thank You for Providing this opportunity.
> chore: added ortelius

- _data/repos.js
added repo link, #81
added BeforeIDieCode repository link.
> added beforeIdieCode repository link

- pages/search/[lang].js
Added the functionality of sorting. solving the issue #92
- Added sorting functionality to the search results page.
- Implemented sorting functions for various criteria.
- Updated the UI to include a dropdown for selecting the sorting option.
- [✅] Starred this repo ⭐.
- [✅] Code adheres to the project's coding standards 💻.
- [✅] No sensitive information is inadvertently exposed 👀.
- [✅] Commit history is clear and concise 📃.
> Add sorting functionality to Search page

- pages/search/[lang].js
This reverts commit 437ec4a1cdde3e70434df6bd33fe234437b867d7.
> Revert "Add sorting functionality to Search page (#106) - build"

- pages/search/[lang].js
issues mentioned in pull request #106 is resolved.
Resolved Bug: Fixed a critical bug that previously prevented the application from working properly when changing the language. The issue has been resolved, and users can now seamlessly switch between languages without encountering errors.
> bug resolved.

- _data/repos.js
Add 3 active repo links to `_data/repo.js`. They are:
- falcosidekick
- nocodb
- DocsGPT
> Update repos.js with 3 active repos

- _data/repos.js
> Added two active repo links

- _data/repos.js
added 'Apostrophe' in active repos
> chore: added Apostrophe

- _data/repos.js
Added one active repo
Added Tailwindcss repo which has 73K+ stars and accepting PRs actively.
> added one active repo

- _data/repos.js
- pages/search/[lang].js
[three repos added in the repos.js file](https://github.com/anand346/findissues/commit/8a27761ed65218195bdfe93dd71e0dadae436078)
The problem statement was to add at most three active repos links so the reos.js file is updated as mentioned in the issue
check if the changes made are correct and review the request
check if the changes made are correct and review the request
---
> three repos added in the repos.js file

- _data/repos.js
**Added Three Open Source Projects**
I've added three open-source projects that meet the specified criteria:
1. [Coding Interview University](https://github.com/jwasham/coding-interview-university)
- Stars: 271k
- Open Issues: 44
2. [Developer Roadmap](https://github.com/kamranahmedse/developer-roadmap)
- Stars: 258k
- Open Issues: 620
3. [Build Your Own X](https://github.com/codecrafters-io/build-your-own-x)
- Stars: 227k
- Open Issues: 171
These repositories have more than stars, have been updated recently, and are currently accepting contributions. They cover a wide range of topics and provide valuable resources for learning and contributing to open source.
Please review and merge this pull request. If you have any questions or suggestions, feel free to let me know!
> chore: Added Sahaja

- pages/search/[lang].js
Resolves [43](https://github.com/anand346/findissues/issues/43)
- Add a "Scroll to top" button on the bottom right of the results page, clicking it will scroll to the top 
https://www.loom.com/share/83c2201c461f44ff96dfec16f5f41405 (note: sometimes the video won't play/freezes)
- Don't know what the design of the button should look like, but I'm using the same styles currently in the repo. 
- I'm not too familiar with front-end development, so please let me know if I need to make changes!
> Feat : Add scroll to top

- components/RepoCard.js
- helper/tags.js
> Deleted the hacktoberfest tag and added a bug tag.

- pages/search/[lang].js
Fixed Issues opened on Jun 5: Issues of Repo having 0 stars and forks are showing in the issues result https://github.com/anand346/findissues/issues/6
- modified [lang].js file under search folder
- in function "loadIssues", before pushing "issueObj" in to "allIssues", check whether fork count and star count are greater than 0
- only push into "allIssue" when both fork count and star count are greater than 0
Before changes: there are issues loaded from repos that have 0 stars or 0 forks
After changes: there are no more issues loaded from repos that have 0 stars or 0 forks
Please check if the changes meets standards and expectations! Thank you!
Please check if the changes meets standards and expectations! Thank you
Add any pertinent information or context about the PR that may aid …
> load repo only if fork count and star count both greater than 0

- _data/repos.js
#81 
- [Pytorch](https://pytorch.org/): https://github.com/pytorch/pytorch
- [Next.js](https://nextjs.org/): https://github.com/vercel/next.js
- [OpenMetadata](https://open-metadata.org/): https://github.com/open-metadata/OpenMetadata
> added pytorch, next.js and OpenMetadata

- components/IssuesCard.js
**Fixed issue#134**
The onClick event on the issue card does not fire when clicking on issue link.
Please check if the code adheres to the repository standards.
> Fix bug in opening duplicate links on clicking issue links

- components/GeneralLayout.js
- components/IssuesCard.js
- components/LandingMain.js
- components/LeftSidebar.js
- components/MainLayout.js
- components/Navbar.js
- components/RepoCard.js
- components/RightSidebar.js
- helper/themeClasses.js
- package-lock.json
- package.json
- pages/active-repos/index.js
- pages/index.js
- pages/search/[lang].js
- tailwind.config.js
Implemented Theme Switching functionality and light mode option [issue#150](https://github.com/anand346/findissues/issues/150#issue-2271099885)
Implemented a ThemeProvider that wraps around the entire application. Added new colors in tailwind.configure.js defined as light/dark_main_primary. Added toggle button in the navigation bar for theme switching and updated the relevant files to use theme-based styling (eg. text-${theme}_main_yellow). Finally, I also made the themeClasses.js file to add all the classnames to the generated by the Tailwind stylesheet to be able to access and update them dynamically in the codebase.
In the video, you can see the theme toggle button in the navigation bar to allow users to switch between dark and light mode. When clicked, the theme of the application …
> Add Light mode option

- _data/repos.js
#81 
Added two active open source projects (augur and odd-platform).
> chore: added augur and odd-platform

- pages/search/[lang].js
Original dropdown does not look consistent with the theme of the site.
- [ x] Starred this repo ⭐.
- [ x] Code adheres to the project's coding standards 💻.
- [ x] No sensitive information is inadvertently exposed 👀.
- [ x] Commit history is clear and concise 📃.
> Change styling of sortissues dropdown

- pages/active-repos/index.js
- pages/search/[lang].js
#142
https://github.com/anand346/findissues/assets/72077931/3b4f517b-aa92-44b6-9366-ac1ba354af9f
> Added scroll to active repos

- pages/index.js
> for -build

- _data/repos.js
This fix is improving the active github repository Link list #81 
I added ddev to the link list. DDEV is an active maintained Repository with a kind community which is open to contributions.
Also see [DDEVs](https://github.com/ddev/ddev) repository for more Info
-
Used this [documentation](https://github.com/anand346/findissues/blob/main/list-active-repo.md) to contribute:
- [ x ] Starred this repo ⭐.
- [ x ] Code adheres to the project's coding standards 💻.
- [ x ] No sensitive information is inadvertently exposed 👀.
- [ x ] Commit history is clear and concise 📃.
-
-
> chore: add ddev

- _data/repos.js
Added two repos:
- Scribe-Data by scribe-org
- hey by heyxyz
> Updated repos.js

- README.md
Fixes #158 - README web app link
> Fixes #158 - README web app link

- _data/repos.js
PR for issue #81 
Add hoppscotch repo link in _data / repos.js
> chore: add hoppscotch link in active repos

- _data/repos.js
add turborepo-template in active repos
> chore: added turborepo-template
